# Generated by Django 5.2.8 on 2025-11-22 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(default='farmer', max_length=20)),
                ('agristack_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
