# Generated by Django 5.2.8 on 2025-11-22 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('user_provided_area', models.CharField(blank=True, max_length=100, null=True)),
                ('calculated_area_sqm', models.FloatField()),
                ('polygon_coordinates', models.JSONField()),
                ('markers', models.JSONField()),
                ('photo_geo', models.JSONField()),
                ('photo_file', models.CharField(blank=True, max_length=300, null=True)),
                ('status', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plots', to='authapp.farmer')),
            ],
        ),
    ]
