# Generated by Django 5.2.8 on 2025-11-22 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_plot'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=100)),
                ('area_acres', models.FloatField()),
                ('sowing_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='Growing', max_length=50)),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to='authapp.plot')),
            ],
        ),
        migrations.CreateModel(
            name='HarvestEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harvested_on', models.DateField(auto_now_add=True)),
                ('harvested_area_acres', models.FloatField(blank=True, null=True)),
                ('harvested_qty', models.FloatField(blank=True, null=True)),
                ('qr_url', models.CharField(blank=True, max_length=255, null=True)),
                ('blockchain_tx', models.CharField(blank=True, max_length=255, null=True)),
                ('crop_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvests', to='authapp.cropcycle')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harvested_on', models.DateField()),
                ('final_yield', models.FloatField(blank=True, null=True)),
                ('qr_url', models.CharField(max_length=255)),
                ('blockchain_tx', models.CharField(max_length=255)),
                ('crop_cycle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authapp.cropcycle')),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.plot')),
            ],
        ),
    ]
